package com.mycompany.model.entity;
// Generated 06.05.2016 18:28:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="register_of_public_association"
)
public class Admin  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String password;
     private Set<AllRecords> allRecordses = new HashSet(0);

    public Admin() {
    }

	
    public Admin(String name, String password) {
        this.name = name;
        this.password = password;
    }
    public Admin(String name, String password, Set<AllRecords> allRecordses) {
       this.name = name;
       this.password = password;
       this.allRecordses = allRecordses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=65535)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="admin")
    public Set<AllRecords> getAllRecordses() {
        return this.allRecordses;
    }
    
    public void setAllRecordses(Set<AllRecords> allRecordses) {
        this.allRecordses = allRecordses;
    }




}


