package com.mycompany.model.entity;
// Generated 06.05.2016 18:28:25 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AllRecords generated by hbm2java
 */
@Entity
@Table(name="all_records"
    ,catalog="register_of_public_association"
)
public class AllRecords  implements java.io.Serializable {


     private Integer id;
     private Admin admin;
     private Date date;
     private String details;
     private Cause cause;

    public AllRecords() {
    }

	
    public AllRecords(Admin admin, Date date) {
        this.admin = admin;
        this.date = date;
    }
    public AllRecords(Admin admin, Date date, String details, Cause cause) {
       this.admin = admin;
       this.date = date;
       this.details = details;
       this.cause = cause;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="admin_id", nullable=false)
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="details", length=65535)
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="allRecords")
    public Cause getCause() {
        return this.cause;
    }
    
    public void setCause(Cause cause) {
        this.cause = cause;
    }




}


