package com.mycompany.model.entity;
// Generated 06.05.2016 18:28:25 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Cause generated by hbm2java
 */
@Entity
@Table(name="cause"
    ,catalog="register_of_public_association"
)
public class Cause  implements java.io.Serializable {


     private int allRecordsId;
     private AllRecords allRecords;
     private String causes;

    public Cause() {
    }

    public Cause(AllRecords allRecords, String causes) {
       this.allRecords = allRecords;
       this.causes = causes;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="allRecords"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="all_records_id", unique=true, nullable=false)
    public int getAllRecordsId() {
        return this.allRecordsId;
    }
    
    public void setAllRecordsId(int allRecordsId) {
        this.allRecordsId = allRecordsId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public AllRecords getAllRecords() {
        return this.allRecords;
    }
    
    public void setAllRecords(AllRecords allRecords) {
        this.allRecords = allRecords;
    }

    
    @Column(name="causes", nullable=false, length=45)
    public String getCauses() {
        return this.causes;
    }
    
    public void setCauses(String causes) {
        this.causes = causes;
    }




}


