package com.mycompany.model.entity;
// Generated 06.05.2016 18:28:25 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Enterprise generated by hbm2java
 */
@Entity
@Table(name="enterprise"
    ,catalog="register_of_public_association"
)
public class Enterprise  implements java.io.Serializable {


     private int usreouCode;
     private PublicAssociation publicAssociation;
     private String name;

    public Enterprise() {
    }

    public Enterprise(int usreouCode, PublicAssociation publicAssociation, String name) {
       this.usreouCode = usreouCode;
       this.publicAssociation = publicAssociation;
       this.name = name;
    }
   
     @Id 

    
    @Column(name="USREOU_code", unique=true, nullable=false)
    public int getUsreouCode() {
        return this.usreouCode;
    }
    
    public void setUsreouCode(int usreouCode) {
        this.usreouCode = usreouCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="public_association_id", nullable=false)
    public PublicAssociation getPublicAssociation() {
        return this.publicAssociation;
    }
    
    public void setPublicAssociation(PublicAssociation publicAssociation) {
        this.publicAssociation = publicAssociation;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


