package com.mycompany.model.entity;
// Generated 06.05.2016 18:28:25 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FourthLevelOfLocation generated by hbm2java
 */
@Entity
@Table(name="fourth_level_of_location"
    ,catalog="register_of_public_association"
)
public class FourthLevelOfLocation  implements java.io.Serializable {


     private FourthLevelOfLocationId id;
     private ThirdLevelOfLocation thirdLevelOfLocation;
     private String name;

    public FourthLevelOfLocation() {
    }

	
    public FourthLevelOfLocation(FourthLevelOfLocationId id, ThirdLevelOfLocation thirdLevelOfLocation) {
        this.id = id;
        this.thirdLevelOfLocation = thirdLevelOfLocation;
    }
    public FourthLevelOfLocation(FourthLevelOfLocationId id, ThirdLevelOfLocation thirdLevelOfLocation, String name) {
       this.id = id;
       this.thirdLevelOfLocation = thirdLevelOfLocation;
       this.name = name;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="code", column=@Column(name="code", nullable=false) ), 
        @AttributeOverride(name="thirdLevelOfLocationCode", column=@Column(name="third_level_of_location_code", nullable=false) ), 
        @AttributeOverride(name="secondLevelOfLocationCode", column=@Column(name="second_level_of_location_code", nullable=false) ), 
        @AttributeOverride(name="firstLevelOfLocationCode", column=@Column(name="first_level_of_location_code", nullable=false) ) } )
    public FourthLevelOfLocationId getId() {
        return this.id;
    }
    
    public void setId(FourthLevelOfLocationId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="third_level_of_location_code", referencedColumnName="code", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="second_level_of_location_code", referencedColumnName="second_level_of_location_code", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="first_level_of_location_code", referencedColumnName="first_level_of_location_code", nullable=false, insertable=false, updatable=false) } )
    public ThirdLevelOfLocation getThirdLevelOfLocation() {
        return this.thirdLevelOfLocation;
    }
    
    public void setThirdLevelOfLocation(ThirdLevelOfLocation thirdLevelOfLocation) {
        this.thirdLevelOfLocation = thirdLevelOfLocation;
    }

    
    @Column(name="name", length=65535)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


