package com.mycompany.model.entity;
// Generated 06.05.2016 18:28:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="person"
    ,catalog="register_of_public_association"
)
public class Person  implements java.io.Serializable {


     private Integer id;
     private Nationality nationality;
     private String name;
     private String series;
     private String number;
     private String dateOfBirth;
     private Set<PublicAssociationHasPerson> publicAssociationHasPersons = new HashSet(0);

    public Person() {
    }

	
    public Person(Nationality nationality, String name) {
        this.nationality = nationality;
        this.name = name;
    }
    public Person(Nationality nationality, String name, String series, String number, String dateOfBirth, Set<PublicAssociationHasPerson> publicAssociationHasPersons) {
       this.nationality = nationality;
       this.name = name;
       this.series = series;
       this.number = number;
       this.dateOfBirth = dateOfBirth;
       this.publicAssociationHasPersons = publicAssociationHasPersons;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nationality_id", nullable=false)
    public Nationality getNationality() {
        return this.nationality;
    }
    
    public void setNationality(Nationality nationality) {
        this.nationality = nationality;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="series", length=45)
    public String getSeries() {
        return this.series;
    }
    
    public void setSeries(String series) {
        this.series = series;
    }

    
    @Column(name="number", length=45)
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }

    
    @Column(name="date_of_birth", length=45)
    public String getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(String dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="person")
    public Set<PublicAssociationHasPerson> getPublicAssociationHasPersons() {
        return this.publicAssociationHasPersons;
    }
    
    public void setPublicAssociationHasPersons(Set<PublicAssociationHasPerson> publicAssociationHasPersons) {
        this.publicAssociationHasPersons = publicAssociationHasPersons;
    }




}


