package com.mycompany.model.entity;
// Generated 06.05.2016 18:28:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Post generated by hbm2java
 */
@Entity
@Table(name="post"
    ,catalog="register_of_public_association"
)
public class Post  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<PublicAssociationHasPerson> publicAssociationHasPersons = new HashSet(0);

    public Post() {
    }

	
    public Post(String name) {
        this.name = name;
    }
    public Post(String name, Set<PublicAssociationHasPerson> publicAssociationHasPersons) {
       this.name = name;
       this.publicAssociationHasPersons = publicAssociationHasPersons;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="post")
    public Set<PublicAssociationHasPerson> getPublicAssociationHasPersons() {
        return this.publicAssociationHasPersons;
    }
    
    public void setPublicAssociationHasPersons(Set<PublicAssociationHasPerson> publicAssociationHasPersons) {
        this.publicAssociationHasPersons = publicAssociationHasPersons;
    }




}


