package com.mycompany.model.entity;
// Generated 06.05.2016 18:28:25 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PublicAssociationHasPersonId generated by hbm2java
 */
@Embeddable
public class PublicAssociationHasPersonId  implements java.io.Serializable {


     private int publicAssociationId;
     private int personId;

    public PublicAssociationHasPersonId() {
    }

    public PublicAssociationHasPersonId(int publicAssociationId, int personId) {
       this.publicAssociationId = publicAssociationId;
       this.personId = personId;
    }
   


    @Column(name="public_association_id", nullable=false)
    public int getPublicAssociationId() {
        return this.publicAssociationId;
    }
    
    public void setPublicAssociationId(int publicAssociationId) {
        this.publicAssociationId = publicAssociationId;
    }


    @Column(name="person_id", nullable=false)
    public int getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(int personId) {
        this.personId = personId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PublicAssociationHasPersonId) ) return false;
		 PublicAssociationHasPersonId castOther = ( PublicAssociationHasPersonId ) other; 
         
		 return (this.getPublicAssociationId()==castOther.getPublicAssociationId())
 && (this.getPersonId()==castOther.getPersonId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPublicAssociationId();
         result = 37 * result + this.getPersonId();
         return result;
   }   


}


