package com.mycompany.model.entity;
// Generated 06.05.2016 18:28:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SecondLevelOfLocation generated by hbm2java
 */
@Entity
@Table(name="second_level_of_location"
    ,catalog="register_of_public_association"
)
public class SecondLevelOfLocation  implements java.io.Serializable {


     private SecondLevelOfLocationId id;
     private FirstLevelOfLocation firstLevelOfLocation;
     private String name;
     private Set<ThirdLevelOfLocation> thirdLevelOfLocations = new HashSet(0);

    public SecondLevelOfLocation() {
    }

	
    public SecondLevelOfLocation(SecondLevelOfLocationId id, FirstLevelOfLocation firstLevelOfLocation) {
        this.id = id;
        this.firstLevelOfLocation = firstLevelOfLocation;
    }
    public SecondLevelOfLocation(SecondLevelOfLocationId id, FirstLevelOfLocation firstLevelOfLocation, String name, Set<ThirdLevelOfLocation> thirdLevelOfLocations) {
       this.id = id;
       this.firstLevelOfLocation = firstLevelOfLocation;
       this.name = name;
       this.thirdLevelOfLocations = thirdLevelOfLocations;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="code", column=@Column(name="code", nullable=false) ), 
        @AttributeOverride(name="firstLevelOfLocationCode", column=@Column(name="first_level_of_location_code", nullable=false) ) } )
    public SecondLevelOfLocationId getId() {
        return this.id;
    }
    
    public void setId(SecondLevelOfLocationId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="first_level_of_location_code", nullable=false, insertable=false, updatable=false)
    public FirstLevelOfLocation getFirstLevelOfLocation() {
        return this.firstLevelOfLocation;
    }
    
    public void setFirstLevelOfLocation(FirstLevelOfLocation firstLevelOfLocation) {
        this.firstLevelOfLocation = firstLevelOfLocation;
    }

    
    @Column(name="name", length=65535)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="secondLevelOfLocation")
    public Set<ThirdLevelOfLocation> getThirdLevelOfLocations() {
        return this.thirdLevelOfLocations;
    }
    
    public void setThirdLevelOfLocations(Set<ThirdLevelOfLocation> thirdLevelOfLocations) {
        this.thirdLevelOfLocations = thirdLevelOfLocations;
    }




}


