package com.mycompany.model.entity;
// Generated 06.05.2016 18:28:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ThirdLevelOfLocation generated by hbm2java
 */
@Entity
@Table(name="third_level_of_location"
    ,catalog="register_of_public_association"
)
public class ThirdLevelOfLocation  implements java.io.Serializable {


     private ThirdLevelOfLocationId id;
     private SecondLevelOfLocation secondLevelOfLocation;
     private String name;
     private Set<FourthLevelOfLocation> fourthLevelOfLocations = new HashSet(0);

    public ThirdLevelOfLocation() {
    }

	
    public ThirdLevelOfLocation(ThirdLevelOfLocationId id, SecondLevelOfLocation secondLevelOfLocation) {
        this.id = id;
        this.secondLevelOfLocation = secondLevelOfLocation;
    }
    public ThirdLevelOfLocation(ThirdLevelOfLocationId id, SecondLevelOfLocation secondLevelOfLocation, String name, Set<FourthLevelOfLocation> fourthLevelOfLocations) {
       this.id = id;
       this.secondLevelOfLocation = secondLevelOfLocation;
       this.name = name;
       this.fourthLevelOfLocations = fourthLevelOfLocations;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="code", column=@Column(name="code", nullable=false) ), 
        @AttributeOverride(name="secondLevelOfLocationCode", column=@Column(name="second_level_of_location_code", nullable=false) ), 
        @AttributeOverride(name="firstLevelOfLocationCode", column=@Column(name="first_level_of_location_code", nullable=false) ) } )
    public ThirdLevelOfLocationId getId() {
        return this.id;
    }
    
    public void setId(ThirdLevelOfLocationId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="second_level_of_location_code", referencedColumnName="code", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="first_level_of_location_code", referencedColumnName="first_level_of_location_code", nullable=false, insertable=false, updatable=false) } )
    public SecondLevelOfLocation getSecondLevelOfLocation() {
        return this.secondLevelOfLocation;
    }
    
    public void setSecondLevelOfLocation(SecondLevelOfLocation secondLevelOfLocation) {
        this.secondLevelOfLocation = secondLevelOfLocation;
    }

    
    @Column(name="name", length=65535)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="thirdLevelOfLocation")
    public Set<FourthLevelOfLocation> getFourthLevelOfLocations() {
        return this.fourthLevelOfLocations;
    }
    
    public void setFourthLevelOfLocations(Set<FourthLevelOfLocation> fourthLevelOfLocations) {
        this.fourthLevelOfLocations = fourthLevelOfLocations;
    }




}


